### ISSUE TITLE
Setup `action.yaml` with proper inputs and outputs.

### ISSUE THREAD

**Issue by dangoslen** [dangoslen/constable-github-action#4]
Document the action expected inputs and ouputs to run. Should also discuss the need for the GitHub Token as an env variable.

**Comment by dangoslen** [comment]
Ideas
```
name: 'Constable'
description: ''
inputs:
outputs:
  grade: # output will be available to future steps
    description: 'Letter grade A - F'
  percentage:
    description: 'Percentage score of checks made'
 explanation:
   description: 'Table of reasons for percentage score given'
runs:
  using: 'node12'
  main: 'dist/index.js'
```
